### ISSUE TITLE
Interfaces with properties typed as a specific enum value throw an error

### ISSUE THREAD

**Issue by marcindobry** [YousefED/typescript-json-schema#122]
When defining an interface with one of the properties being tied to a specific value of an enum instead of an enum type, an error is thrown. The code assumes it only uses EnumDeclaration but this is an EnumMember.
```ts
export enum HTTPStatusCode {
  Ok = 200,
  BadRequest = 400,
  InternalServerError = 500,
};

export interface BrokenSpecificResponse {
  code: HTTPStatusCode.Ok;
};

// This is what it logically means
export interface ExpectedSpecificResponse {
  code: 200;
};
```

```
node typescript-json-schema.js example.ts BrokenSpecificResponse
<repo-path>/typescript-json-schema/typescript-json-schema.js:270
        enm.members.forEach(function (member) {
                   ^

TypeError: Cannot read property 'forEach' of undefined
    at JsonSchemaGenerator.getEnumDefinition (<repo-path>/typescript-json-schema/typescript-json-schema.js:270:20)
    at JsonSchemaGenerator.getTypeDefinition (<repo-path>/typescript-json-schema/typescript-json-schema.js:590:26)
    at JsonSchemaGenerator.getDefinitionForProperty (<repo-path>/typescript-json-schema/typescript-json-schema.js:225:31)
    at <repo-path>/typescript-json-schema/typescript-json-schema.js:436:37
    at Array.reduce (native)
    at JsonSchemaGenerator.getClassDefinition (<repo-path>/typescript-json-schema/typescript-json-schema.js:434:45)
    at JsonSchemaGenerator.getTypeDefinition (<repo-path>/typescript-json-schema/typescript-json-schema.js:597:26)
    at JsonSchemaGenerator.getSchemaForSymbol (<repo-path>/typescript-json-schema/typescript-json-schema.js:614:24)
    at generateSchema (<repo-path>/typescript-json-schema/typescript-json-schema.js:742:32)
    at exec (<repo-path>/typescript-json-schema/typescript-json-schema.js:772:22)
```

**Comment by marcindobry** [comment]
Closing since the solution got merged.
