### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by j-oliveras** [YousefED/typescript-json-schema#215]
Fails with this call-stack:
```
TypeError: Cannot read property 'length' of undefined
    at Object.exec (node_modules\typescript-json-schema\typescript-json-schema.js:940:26)
    at Object.run (node_modules\typescript-json-schema\typescript-json-schema-cli.js:43:30)
    at Object.<anonymous> (node_modules\typescript-json-schema\bin\typescript-json-schema:3:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
```

The top call-stack line is:
https://github.com/YousefED/typescript-json-schema/blob/e767ab71dbfc38bd2cdc80a31f618ba1fdf08a7c/typescript-json-schema.ts#L1138

One solution can be change it to:
```ts
if (args.include && args.include.length > 0) {
```

Node 8.11.1 (win 64 bits).

**Comment by arielshaqed** [comment]
Ouch, this was introduced in my #211.  The patch should fix it.

## Workaround
I was unable to find a workaround with `0.24.1`.  So please revert:
`npm install typescript-json-schema@0.23.0`

**Comment by chrisjansson** [comment]
I ran into this using 0.24.1

I think the root cause is this argument declaration in yargs. The argument include should get a default value of ````[]```` and never be undefined as seen here.

https://github.com/YousefED/typescript-json-schema/blob/922d9d6341487ae8fc999d4a4cbb95dc2ae04819/typescript-json-schema-cli.ts#L39

The call to default should however be `````"include"`````and not ````*````

    .array("include").default("include", defaultArgs.include)
