### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by HoldYourWaffle** [YousefED/typescript-json-schema#284]
I was planning on investigating a possible fix for #283, but sadly the tests fail without me changing anything.

```
82 passing (2m)
  5 failing

  1) schema
       type aliases
         type-alias-single-annotated should create correct schema:

      The schema is not as expected
      + expected - actual

       {
         "$schema": "http://json-schema.org/draft-07/schema#"
      +  "description": "This is a description"
      +  "maxLength": 24
      +  "minLength": 10
      +  "pattern": "^mystring-[a-zA-Z0-9]+$"
         "type": "string"
       }

      at Context.<anonymous> (test\schema.test.ts:29:16)

  2) schema
       unions and intersections
         type-intersection-recursive should create correct schema:

      The schema is not as expected
      + expected - actual

       {
         "$schema": "http://json-schema.org/draft-07/schema#"
      -  "definitions": {}
      +  "definitions": {
      +    "ChildFoo": {
      +      "type": "object"
      +    }
      +    "Foo": {
      +      "properties": {
      +        "childFoos": {
      +          "allOf": [
      +            {
      +              "$ref": "#/definitions/Foo"
      +            }
      +            {
      +              "$ref": "#/definitions/ChildFoo"
      +            }
      +          ]
      +        }
      +      }
      +      "required": [
      +        "childFoos"
      +      ]
      +      "type": "object"
      +    }
      +  }
       }

      at Context.<anonymous> (test\schema.test.ts:29:16)

  3) schema
       other
         generate-all-types should create correct schema:

      The schema is not as expected
      + expected - actual

       {
         "$schema": "http://json-schema.org/draft-07/schema#"
      -  "definitions": {}
      +  "definitions": {
      +    "MyEnum": {
      +      "enum": [
      +        0
      +      ]
      +      "type": "number"
      +    }
      +    "MyInterface": {
      +      "type": "object"
      +    }
      +    "MyObject": {
      +      "type": "object"
      +    }
      +  }
       }

      at Context.<anonymous> (test\schema.test.ts:29:16)

  4) schema
       other
         unique-names should create correct schema:
     Error: ENOENT: no such file or directory, open 'test/programs/unique-names/schema.MyObject.6aa2b6a1.json'
      at Object.openSync (fs.js:436:3)
      at Object.readFileSync (fs.js:341:35)
      at Context.<anonymous> (test\schema.test.ts:53:24)

  5) schema
       other
         user-symbols should create correct schema:

      The schema is not as expected
      + expected - actual

       {
         "$schema": "http://json-schema.org/draft-07/schema#"
      -  "definitions": {}
      +  "definitions": {
      +    "Context": {
      +      "properties": {
      +        "ip": {
      +          "type": "string"
      +        }
      +      }
      +      "required": [
      +        "ip"
      +      ]
      +      "type": "object"
      +    }
      +  }
       }

      at Context.<anonymous> (test\schema.test.ts:29:16)

npm ERR! Test failed.  See above for more details.
```

Am I doing something wrong? This doesn't look like a platform related issue to me, so I'm not sure why [Travis](https://travis-ci.org/YousefED/typescript-json-schema) would think everything is fine when there are clear *issues* when I run the tests.

**Comment by domoritz** [comment]
Hmm, I just tried it locally and things worked fine. Can you make sure you installed the same dependencies (yarn) and try a clean clone?

**Comment by HoldYourWaffle** [comment]
I tried installing with `yarn` instead of `npm`, a new clone and a new clone on a different machine but nothing changed.
I noticed travis only runs on node 11, but I'm on node 10. Maybe that could be something? To me it seems unlikely that a different node version causes JSON blocks to go missing, but you never know.

**Comment by domoritz** [comment]
Hmm, sorry to hear that. I don't really know how to help but let me know if there is something I can do.
