### ISSUE TITLE
Mapped types with generic indexing failing.

### ISSUE THREAD

**Issue by avatarneil** [YousefED/typescript-json-schema#301]
The below code throws an error when attempting to generate a schema for type `Thing`. This is valid Typescript, and the compiler parses it with no issues.

Sample Code:
source.ts: 
```Typescript
export const FOO_MAP = {
  foo: { bar: "bar", biz: "biz" },
  ex: { potato: "potato" }
};
```

defs.d.ts:
```Typescript
import { FOO_MAP } from "./source";

interface Thing {
  foos: { [S in keyof typeof FOO_MAP]: (keyof typeof FOO_MAP[S])[] | [] };
}
```
Console Command: typescript-json-schema "defs.d.ts" Thing
Error: 
```
/Users/neilgoldader/.config/yarn/global/node_modules/typescript-json-schema/dist/typescript-json-schema.js:244
            var fixedTypes = elemTypes.map(function (elType) { return _this.getTypeDefinition(elType); });
                                       ^

TypeError: Cannot read property 'map' of undefined
    at JsonSchemaGenerator.getDefinitionForRootType (/Users/neilgoldader/.config/yarn/global/node_modules/typescript-json-schema/dist/typescript-json-schema.js:244:40)
    at JsonSchemaGenerator.getTypeDefinition (/Users/neilgoldader/.config/yarn/global/node_modules/typescript-json-schema/dist/typescript-json-schema.js:766:26)
    at JsonSchemaGenerator.getUnionDefinition (/Users/neilgoldader/.config/yarn/global/node_modules/typescript-json-schema/dist/typescript-json-schema.js:457:32)
    at JsonSchemaGenerator.getTypeDefinition (/Users/neilgoldader/.config/yarn/global/node_modules/typescript-json-schema/dist/typescript-json-schema.js:737:26)
    at JsonSchemaGenerator.getDefinitionForProperty (/Users/neilgoldader/.config/yarn/global/node_modules/typescript-json-schema/dist/typescript-json-schema.js:340:31)
    at /Users/neilgoldader/.config/yarn/global/node_modules/typescript-json-schema/dist/typescript-json-schema.js:614:37
    at Array.reduce (<anonymous>)
    at JsonSchemaGenerator.getClassDefinition (/Users/neilgoldader/.config/yarn/global/node_modules/typescript-json-schema/dist/typescript-json-schema.js:612:45)
    at JsonSchemaGenerator.getTypeDefinition (/Users/neilgoldader/.config/yarn/global/node_modules/typescript-json-schema/dist/typescript-json-schema.js:776:26)
    at JsonSchemaGenerator.getDefinitionForProperty (/Users/neilgoldader/.config/yarn/global/node_modules/typescript-json-schema/dist/typescript-json-schema.js:340:31)
```

**Comment by karcass** [comment]
This may address it:

```typescript-json-schema.js:243            var elemTypes = tupleType.elementTypes || propertyType.typeArguments || [];```

**Comment by avatarneil** [comment]
The above comment seems to be pretty close to the solution, when I run the modified code I get:
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "{foo:[]|(\"bar\"|\"biz\")[];ex:[]|\"potato\"[];}": {
            "properties": {
                "ex": {
                    "anyOf": [
                        {
                            "additionalItems": {
                                "anyOf": [
                                ]
                            },
                            "items": [
                            ],
                            "minItems": 0,
                            "type": "array"
                        },
                        {
                            "items": {
                                "enum": [
                                    "potato"
                                ],
                                "type": "string"
                            },
                            "type": "array"
                        }
                    ]
                },
                "foo": {
                    "anyOf": [
                        {
                            "additionalItems": {
                                "anyOf": [
                                ]
                            },
                            "items": [
                            ],
                            "minItems": 0,
                            "type": "array"
                        },
                        {
                            "items": {
                                "enum": [
                                    "bar",
                                    "biz"
                                ],
                                "type": "string"
                            },
                            "type": "array"
                        }
                    ]
                }
            },
            "type": "object"
        }
    },
    "properties": {
        "foos": {
            "$ref": "#/definitions/{foo:[]|(\"bar\"|\"biz\")[];ex:[]|\"potato\"[];}"
        }
    },
    "type": "object"
}
```

It seems like it's not properly resolving the name of `FOO_MAP` though, and is instead referring to it as `{foo:[]|(\"bar\"|\"biz\")[];ex:[]|\"potato\"[];}`.

**Comment by 282159468** [comment]
same issue
