### ISSUE TITLE
Wrong behavior of * operator in cli

### ISSUE THREAD

**Issue by bogdan** [YousefED/typescript-json-schema#309]
Given the following files:

./lib/types/ZnsResolutionType.ts:

``` typescript
interface CurrencyResolution {
  address: string
}
export default interface ZnsResolutionType {
  crypto: {
    ADA?: CurrencyResolution,
    BTC?: CurrencyResolution,
    EOS?: CurrencyResolution,
    ETH?: CurrencyResolution,
    XLM?: CurrencyResolution,
    XRP?: CurrencyResolution,
    ZIL?: CurrencyResolution,
  }
}
```

./lib/types/ResellerOrderType.ts

``` typescript
import ZnsResolutionType from './ZnsResolutionType'

interface OrderItem {
  name: string;
  owner: string;
  resolution?: ZnsResolutionType;
}
export default interface ResellerOrderType {
  domains: OrderItem[]
}
```

Running the following command results in an error:

```
$     typescript-json-schema  lib/types/* ResellerOrderType
/Users/bogdan/.nvm/versions/node/v10.15.3/lib/node_modules/typescript-json-schema/dist/typescript-json-schema.js:795
            throw new Error("type " + symbolName + " not found");
            ^

Error: type lib/types/ZnsResolutionType.ts not found
    at JsonSchemaGenerator.getSchemaForSymbol (/Users/bogdan/.nvm/versions/node/v10.15.3/lib/node_modules/typescript-json-schema/dist/typescript-json-schema.js:795:19)
    at generateSchema (/Users/bogdan/.nvm/versions/node/v10.15.3/lib/node_modules/typescript-json-schema/dist/typescript-json-schema.js:967:26)
    at Object.exec (/Users/bogdan/.nvm/versions/node/v10.15.3/lib/node_modules/typescript-json-schema/dist/typescript-json-schema.js:1016:22)
    at Object.run (/Users/bogdan/.nvm/versions/node/v10.15.3/lib/node_modules/typescript-json-schema/dist/typescript-json-schema-cli.js:48:30)
    at Object.<anonymous> (/Users/bogdan/.nvm/versions/node/v10.15.3/lib/node_modules/typescript-json-schema/bin/typescript-json-schema:3:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

**Comment by domoritz** [comment]
You shell expands * automatically. 

Please try `typescript-json-schema  ./lib/types/ResellerOrderType.ts ResellerOrderType` instead.

**Comment by bogdan** [comment]
Generating a schema for multiple types is very slow if we use a separated CLI call for each type.
Is there an intended way to generate multiple schemas with a single CLI call?

**Comment by domoritz** [comment]
Yes, you can pass `*` (make sure to escape for your shell) as the types argument and pass your tsconfig instead of a file.

**Comment by bogdan** [comment]
I tried that and it seems to be close to what I want. The last problem I have is that `ZnsResolutionType` is set to `definitions.default` but not `definitions.ZnsResolutionType`.

It is weird that `ResellerOrderType` is exported correctly.
Is it possible to define `ZnsResolutionType` with the matching name but not `default`?

Here is the command I run:

```
typescript-json-schema  --required "lib/types/*Type.ts" "*" 
```

And the output https://gist.github.com/9cc6a571284b561084d50329bb018811

**Comment by domoritz** [comment]
Aliasing is super tricky and we don't always do a good job. I'd recommend not using a default export or looking into submitting a pull request that fixes the behavior.

**Comment by bogdan** [comment]
So, is it confirmed as a bug?

**Comment by domoritz** [comment]
The generated spec isn't incorrect but certainly not as meaningful as if we correctly resolve the alias. I'd say improving this would be an enhancement.
