### ISSUE TITLE
Crash when array in schema should be empty

### ISSUE THREAD

**Issue by l-jonas** [YousefED/typescript-json-schema#320]
reproduction:

- create new directory
- run ``npm i typescript-json-schema``
- create a file called ``test.ts``:

```
interface Test {
  test: []
}
```

- run ``./node_modules/.bin/typescript-json-schema ./test.ts Test`` (assuming Linux)
- output:

```
            var fixedTypes = elemTypes.map(function (elType) { return _this.getTypeDefinition(elType); });
                                       ^

TypeError: Cannot read property 'map' of undefined
    at JsonSchemaGenerator.getDefinitionForRootType ([directory]/node_modules/typescript-json-schema/dist/typescript-json-schema.js:255:40)
    at JsonSchemaGenerator.getTypeDefinition ([directory]/node_modules/typescript-json-schema/dist/typescript-json-schema.js:781:26)
    at JsonSchemaGenerator.getDefinitionForProperty ([directory]/node_modules/typescript-json-schema/dist/typescript-json-schema.js:351:31)
    at [directory]/node_modules/typescript-json-schema/dist/typescript-json-schema.js:629:37
    at Array.reduce (<anonymous>)
    at JsonSchemaGenerator.getClassDefinition ([directory]/node_modules/typescript-json-schema/dist/typescript-json-schema.js:627:45)
    at JsonSchemaGenerator.getTypeDefinition ([directory]/node_modules/typescript-json-schema/dist/typescript-json-schema.js:791:26)
    at JsonSchemaGenerator.getSchemaForSymbol ([directory]/node_modules/typescript-json-schema/dist/typescript-json-schema.js:808:24)
    at generateSchema ([directory]/node_modules/typescript-json-schema/dist/typescript-json-schema.js:978:26)
    at Object.exec ([directory]/node_modules/typescript-json-schema/dist/typescript-json-schema.js:1027:22)
```

versions (according to package-lock.json):

- typescript 3.6.4
- typescript-json-schema 0.40.0

**Comment by domoritz** [comment]
Thank you for the clear bug report.
