### ISSUE TITLE
Unexpected token * in `import * as TJS from 'typescript-json-schema';`

### ISSUE THREAD

**Issue by Dok11** [YousefED/typescript-json-schema#321]
```
$ ts-node tjs-generator.ts
\data\main\tjs-generator.ts:1
(function (exports, require, module, __filename, __dirname) { import * as TJS from 'typescript-json-schema';
                                                                     ^

SyntaxError: Unexpected token *
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module.m._compile (C:\Users\dok\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:493:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\dok\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:496:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

in tjs-generator.ts
```ts
import * as TJS from 'typescript-json-schema';
const path = require('path');

const program = TJS.getProgramFromFiles(
  [path.resolve('/src/app/shared/api-schemas.ts')],
  { strictNullChecks: true },
  './'
);
```

And
```
$ ts-node tjs-generator.ts
\data\main\tjs-generator.ts:1
(function (exports, require, module, __filename, __dirname) { import { resolve } from 'path';
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module.m._compile (C:\Users\dok\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:493:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\dok\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:496:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

in tjs-generator.ts
```ts
import { resolve } from 'path';
import * as TJS from 'typescript-json-schema';

const program = TJS.getProgramFromFiles(
  [resolve('/src/app/shared/api-schemas.ts')],
  { strictNullChecks: true },
  './'
);
```

My env
```
Windows 10
Nodejs v.10.10.0
```

Can someone suggest me what I can do to fix this trouble?

**Comment by Dok11** [comment]
As I realize the trouble in ts-node and tsconfig.json

I try run it in angular application with exist tsconfig.json and seems it not compatible with TJS.
How avoid this trouble?

Structure of files
![image](https://user-images.githubusercontent.com/2697890/68481902-6a72d480-0249-11ea-8f3c-dac862b43758.png)

And tsonfig.json
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "downlevelIteration": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
```

**Comment by domoritz** [comment]
Your bundler doesn’t seem to support es2015. Can you upgrade to a bundler that supports the new es6 style imports? Alternatively, modify the target to es5 in your tsconfig or use Babel to preprocess the files.

**Comment by Dok11** [comment]
@domoritz 
Does exist way to fix trouble without edit tsconfig.json?
Maybe some ability to define custom tsconfig right in command line lik this `ts-node tjs-generator.ts --useConfig=./custom-tsconfig.json`?

**Comment by domoritz** [comment]
Oh, sorry I misunderstood the issue. I thought you compiled the library rather than using the tool to generate a schema for some typings. Ignore what I said earlier. 

Yes, you can pass a custom tsconfig to the library with -f.

**Comment by Dok11** [comment]
Can you provide a reference `tsconfig.json` which I should use for run TJS?

> Yes, you can pass a custom tsconfig to the library with -f.

Thanks! I did not known about this feature

**Comment by domoritz** [comment]
Sorry, again ignore me. I wasn't quite awake yet. I thought that this repo was https://github.com/vega/ts-json-schema-generator all along. 🤦‍♂ 

In this project, you just pass the tsconfig directly. `typescript-json-schema project/directory/tsconfig.json TYPE` is from the docs. The default args at in https://github.com/YousefED/typescript-json-schema/blob/master/typescript-json-schema.ts#L17.
