### ISSUE TITLE
Avoid infinite loops

### ISSUE THREAD

**Issue by domoritz** [YousefED/typescript-json-schema#33]
With references we should be able to support interfaces that reference themselves, The easiest fix would be to only recurse if the type does not yet exist in the map of definitions.

**Comment by YousefED** [comment]
Should be supported now in https://github.com/YousefED/typescript-json-schema/tree/refactor-and-recursion-support

There have been quite some changes (large cleanup necessary). Would you mind testing this branch on your usage scenarios before I merge it?

**Comment by domoritz** [comment]
Awesome!

I linked the version from your branch into vega-lite and ran `npm run schema`

```
$ npm run schema

> vega-lite@1.0.8 schema /Users/domoritz/Developer/UW/vega-lite
> typescript-json-schema --required true src/spec.ts Spec > vega-lite-schema.json

/Users/domoritz/Developer/UW/typescript-json-schema/typescript-json-schema.js:212
            if (props.length == 0 && clazz.members.length == 1 && clazz.members[0].kind == ts.SyntaxKind.IndexSignature) {
                                                  ^

TypeError: Cannot read property 'length' of undefined
    at JsonSchemaGenerator.getClassDefinition (/Users/domoritz/Developer/UW/typescript-json-schema/typescript-json-schema.js:212:51)
    at JsonSchemaGenerator.getTypeDefinition (/Users/domoritz/Developer/UW/typescript-json-schema/typescript-json-schema.js:289:26)
    at JsonSchemaGenerator.getDefinitionForProperty (/Users/domoritz/Developer/UW/typescript-json-schema/typescript-json-schema.js:136:35)
    at /Users/domoritz/Developer/UW/typescript-json-schema/typescript-json-schema.js:238:41
    at Array.reduce (native)
    at JsonSchemaGenerator.getClassDefinition (/Users/domoritz/Developer/UW/typescript-json-schema/typescript-json-schema.js:236:49)
    at JsonSchemaGenerator.getTypeDefinition (/Users/domoritz/Developer/UW/typescript-json-schema/typescript-json-schema.js:289:26)
    at JsonSchemaGenerator.getDefinitionForProperty (/Users/domoritz/Developer/UW/typescript-json-schema/typescript-json-schema.js:136:35)
    at /Users/domoritz/Developer/UW/typescript-json-schema/typescript-json-schema.js:238:41
    at Array.reduce (native)
```

**Comment by YousefED** [comment]
thanks. I'm seeing a bunch of other issues now, looking into it and will
keep you posted

**Comment by YousefED** [comment]
Can you check the latest version for any regressions?

**Comment by domoritz** [comment]
Hmm, I'm still having problems with an exceeded call stack. This is with version 1c0b298. 

```ts
export interface FacetSpec extends BaseSpec {
  facet: Facet;
  spec: FacetSpec | UnitSpec
}
```

```
> vega-lite@1.0.8 schema /Users/domoritz/Developer/UW/vega-lite
> typescript-json-schema --required true --topRef true src/spec.ts Spec > vega-lite-schema.json

/usr/local/lib/node_modules/typescript-json-schema/node_modules/typescript/lib/typescript.js:1137
        return hasOwnProperty.call(map, key);
                              ^

RangeError: Maximum call stack size exceeded
    at Object.hasOwnProperty (native)
    at hasProperty (/usr/local/lib/node_modules/typescript-json-schema/node_modules/typescript/lib/typescript.js:1137:31)
    at Object.lookUp (/usr/local/lib/node_modules/typescript-json-schema/node_modules/typescript/lib/typescript.js:1193:16)
    at getAccessibleSymbolChainFromSymbolTable (/usr/local/lib/node_modules/typescript-json-schema/node_modules/typescript/lib/typescript.js:15950:37)
    at forEachSymbolTableInScope (/usr/local/lib/node_modules/typescript-json-schema/node_modules/typescript/lib/typescript.js:15923:20)
    at getAccessibleSymbolChain (/usr/local/lib/node_modules/typescript-json-schema/node_modules/typescript/lib/typescript.js:15976:24)
    at walkSymbol (/usr/local/lib/node_modules/typescript-json-schema/node_modules/typescript/lib/typescript.js:16240:53)
    at buildSymbolDisplay (/usr/local/lib/node_modules/typescript-json-schema/node_modules/typescript/lib/typescript.js:16271:21)
    at writeType (/usr/local/lib/node_modules/typescript-json-schema/node_modules/typescript/lib/typescript.js:16299:25)
    at Object.buildTypeDisplay (/usr/local/lib/node_modules/typescript-json-schema/node_modules/typescript/lib/typescript.js:16279:24)
```

**Comment by YousefED** [comment]
Hmm I can't reproduce this unfortunately (I tried it with the latest vega and changed FacetSpec to match your comment). 

Can you
1) double check version of TJS you're using? (https://github.com/YousefED/typescript-json-schema/commit/1c0b298f617eb803d045b8371d811ecf83b64da1 should be correct indeed)
2) provide a test case reproducing the issue?

**Comment by domoritz** [comment]
Interesting. It works if I put your branch in the package.json but not if I link it. https://github.com/vega/vega-lite/commit/43fad48c08f7f89ef04a1029b845d4006db13420

Anyway, looks good now!

**Comment by YousefED** [comment]
Ok. Merged into master. Think we're good, but keep an eye on any regressions!

**Comment by Chris-Currin** [comment]
seems to have cropped up for me, do you mind testing it your side again?
Perhaps a purely typescript issue jusdging by the logs?

`"typescript": "^2.4.1",
 "typescript-json-schema": "^0.17.0",

C:\dev\race_backend\node_modules\typescript\lib\typescript.js:2268
        var iterator = map.entries();
                           ^
RangeError: Maximum call stack size exceeded
    at Object.MapIterator (native)
    at Map.entries (native)
    at Object.forEachEntry (C:\dev\race_backend\node_modules\typescript\lib\typescript.js:2268:28)
    at trySymbolTable (C:\dev\race_backend\node_modules\typescript\lib\typescript.js:24495:31)
    at getAccessibleSymbolChainFromSymbolTableWorker (C:\dev\race_backend\node_modules\typescript\lib\typescript.js:24468:30)
    at C:\dev\race_backend\node_modules\typescript\lib\typescript.js:24508:101
    at Object.forEachEntry (C:\dev\race_backend\node_modules\typescript\lib\typescript.js:2271:26)
    at trySymbolTable (C:\dev\race_backend\node_modules\typescript\lib\typescript.js:24495:31)
    at getAccessibleSymbolChainFromSymbolTableWorker (C:\dev\race_backend\node_modules\typescript\lib\typescript.js:24468:30)
    at getAccessibleSymbolChainFromSymbolTable (C:\dev\race_backend\node_modules\typescript\lib\typescript.js:24461:24)

`
