### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by JoJoor** [YousefED/typescript-json-schema#339]
### this report when a class has a (HTMLCanvasElement) property

```
RangeError: Maximum call stack size exceeded
    at JsonSchemaGenerator.getDefinitionForRootType (/home/joelee/projects/richlox-engine/node_modules/typescript-json-schema/typescript-json-schema.ts:527:59)
    at JsonSchemaGenerator.getTypeDefinition (/home/joelee/projects/richlox-engine/node_modules/typescript-json-schema/typescript-json-schema.ts:1077:26)
    at JsonSchemaGenerator.getDefinitionForRootType (/home/joelee/projects/richlox-engine/node_modules/typescript-json-schema/typescript-json-schema.ts:527:59)
    at JsonSchemaGenerator.getTypeDefinition (/home/joelee/projects/richlox-engine/node_modules/typescript-json-schema/typescript-json-schema.ts:1077:26)
    at JsonSchemaGenerator.getDefinitionForRootType (/home/joelee/projects/richlox-engine/node_modules/typescript-json-schema/typescript-json-schema.ts:527:59)
    at JsonSchemaGenerator.getTypeDefinition (/home/joelee/projects/richlox-engine/node_modules/typescript-json-schema/typescript-json-schema.ts:1077:26)
    at JsonSchemaGenerator.getDefinitionForRootType (/home/joelee/projects/richlox-engine/node_modules/typescript-json-schema/typescript-json-schema.ts:527:59)
    at JsonSchemaGenerator.getTypeDefinition (/home/joelee/projects/richlox-engine/node_modules/typescript-json-schema/typescript-json-schema.ts:1077:26)
    at JsonSchemaGenerator.getDefinitionForRootType (/home/joelee/projects/richlox-engine/node_modules/typescript-json-schema/typescript-json-schema.ts:527:59)
    at JsonSchemaGenerator.getTypeDefinition (/home/joelee/projects/richlox-engine/node_modules/typescript-json-schema/typescript-json-schema.ts:1077:26)
error Command failed with exit code 1.
```

**Comment by domoritz** [comment]
Fixed in https://github.com/YousefED/typescript-json-schema/pull/383
