### ISSUE TITLE
Fails on string literal union types

### ISSUE THREAD

**Issue by arosequist** [YousefED/typescript-json-schema#42]
This seems to fail when using a union of [string literal types](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#string-literal-types).

```ts
interface Test {
    first: 'a'; // works
    second: 'a' | 'b'; // fails
}
```

The error is:

```
/usr/lib/node_modules/typescript-json-schema/node_modules/typescript/lib/typescript.js:15712
            return symbol.parent ? getFullyQualifiedName(symbol.parent) + "." + symbolToString(symbol) : symbolToString(symbol);
                         ^

TypeError: Cannot read property 'parent' of null
    at Object.getFullyQualifiedName (/usr/lib/node_modules/typescript-json-schema/node_modules/typescript/lib/typescript.js:15712:26)
    at JsonSchemaGenerator.getTypeDefinition (/usr/lib/node_modules/typescript-json-schema/typescript-json-schema.js:315:35)
    at JsonSchemaGenerator.getDefinitionForProperty (/usr/lib/node_modules/typescript-json-schema/typescript-json-schema.js:154:35)
    at /usr/lib/node_modules/typescript-json-schema/typescript-json-schema.js:258:41
    at Array.reduce (native)
    at JsonSchemaGenerator.getClassDefinition (/usr/lib/node_modules/typescript-json-schema/typescript-json-schema.js:256:49)
    at JsonSchemaGenerator.getTypeDefinition (/usr/lib/node_modules/typescript-json-schema/typescript-json-schema.js:356:26)
    at JsonSchemaGenerator.getDefinitionForRootType (/usr/lib/node_modules/typescript-json-schema/typescript-json-schema.js:131:49)
    at JsonSchemaGenerator.getTypeDefinition (/usr/lib/node_modules/typescript-json-schema/typescript-json-schema.js:350:26)
    at JsonSchemaGenerator.getDefinitionForProperty (/usr/lib/node_modules/typescript-json-schema/typescript-json-schema.js:154:35)
```

**Comment by arosequist** [comment]
I just noticed [`typescript-json-schema/test/programs/string-literals/main.ts`](https://github.com/YousefED/typescript-json-schema/blob/master/test/programs/string-literals/main.ts), which seems to cover this scenario. I'll do some more digging to isolate the specific situation.

**Comment by arosequist** [comment]
It works if the enum list is separated into its own type, and fails if it's declared inline.

Works:
```ts
type result = "ok" | "fail" | "abort";

class MyObject {
	foo: result
}
```

Fails:
```ts
class MyObject {
	foo: "ok" | "fail" | "abort";
}
```

Unfortunately, I don't know enough about the internals to know how easy of a fix this is.

**Comment by YousefED** [comment]
@SupernaviX if this is still an issue and you have fixed it, would you mind submitting a PR with proper tests?

**Comment by SupernaviX** [comment]
I did, you've already merged it https://github.com/YousefED/typescript-json-schema/pull/45

**Comment by YousefED** [comment]
My bad! Thanks!
