### ISSUE TITLE
Cannot find module 'tslib' @0.53.1

### ISSUE THREAD

**Issue by SimonLdj** [YousefED/typescript-json-schema#483]
Hi, 
since version 0.53.1 any command fails with `Cannot find module 'tslib'` error
checking `npx typescript-json-schema@0.53.0` working fine.

full stack trace: 
```
~ >npx typescript-json-schema@0.53.1                                                                                                                                                                            [1]
Need to install the following packages:
  typescript-json-schema@0.53.1
Ok to proceed? (y) y
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'tslib'
Require stack:
- /Users/username/.npm/_npx/fc767c80b0695a60/node_modules/path-equal/cjs/index.js
- /Users/username/.npm/_npx/fc767c80b0695a60/node_modules/typescript-json-schema/dist/typescript-json-schema.js
- /Users/username/.npm/_npx/fc767c80b0695a60/node_modules/typescript-json-schema/dist/typescript-json-schema-cli.js
- /Users/username/.npm/_npx/fc767c80b0695a60/node_modules/typescript-json-schema/bin/typescript-json-schema
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/username/.npm/_npx/fc767c80b0695a60/node_modules/path-equal/cjs/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/username/.npm/_npx/fc767c80b0695a60/node_modules/path-equal/cjs/index.js',
    '/Users/username/.npm/_npx/fc767c80b0695a60/node_modules/typescript-json-schema/dist/typescript-json-schema.js',
    '/Users/username/.npm/_npx/fc767c80b0695a60/node_modules/typescript-json-schema/dist/typescript-json-schema-cli.js',
    '/Users/username/.npm/_npx/fc767c80b0695a60/node_modules/typescript-json-schema/bin/typescript-json-schema'
  ]
}
```

**Comment by dominic-simplan** [comment]
Same here.

**Comment by BalaM314** [comment]
Same issue, cannot find tslib. Installed it globally and works. I'm pretty sure this is because they forgot to add it to the package.json...

**Comment by BalaM314** [comment]
Actually, the issue seems to be with unional/path-equal .

**Comment by BalaM314** [comment]
Fixed, please close
