### ISSUE TITLE
ERR_INVALID_ARG_TYPE when using -o or --out flag

### ISSUE THREAD

**Issue by cesarvspr** [YousefED/typescript-json-schema#491]
### This works well
```shell

typescript-json-schema "*.ts" modelName

```

### This raises error:

```
typescript-json-schema "*.ts" modelName -o
```

or 

```
typescript-json-schema "*.ts" modelName --out
```

the error: 
```
❯ typescript-json-schema "*.ts" modelName --out
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (true)
    at new NodeError (node:internal/errors:388:5)
    at validateString (node:internal/validators:114:11)
    at Object.dirname (node:path:1276:5)
    at /home/notme4/.nvm/versions/node/v18.4.0/lib/node_modules/typescript-json-schema/dist/typescript-json-schema.js:1321:39
    at new Promise (<anonymous>)
    at /home/notme4/.nvm/versions/node/v18.4.0/lib/node_modules/typescript-json-schema/dist/typescript-json-schema.js:1319:28
    at step (/home/notme4/.nvm/versions/node/v18.4.0/lib/node_modules/typescript-json-schema/dist/typescript-json-schema.js:44:23)
    at Object.next (/home/notme4/.nvm/versions/node/v18.4.0/lib/node_modules/typescript-json-schema/dist/typescript-json-schema.js:25:53)
    at /home/notme4/.nvm/versions/node/v18.4.0/lib/node_modules/typescript-json-schema/dist/typescript-json-schema.js:19:71
    at new Promise (<anonymous>) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.4.0

```

Given current .readme I expected -o flag to enable a schema to be written in a file.

**Comment by cesarvspr** [comment]
Figured it out. 

The argument should have a name for the file 

```
typescript-json-schema "*.ts" modelName -o filename

```
