### ISSUE TITLE
Getting UnhandledPromiseRejectionWarning: Error: No output definition error

### ISSUE THREAD

**Issue by garyutum** [YousefED/typescript-json-schema#540]
When I am trying to generate the schema, I am getting the following error. 
```
Cannot find type definition file for 'moment'.
  The file is in the program because:
    Entry point for implicit type library 'moment'
(node:9434) UnhandledPromiseRejectionWarning: Error: No output definition. Probably caused by errors prior to this?
    at /Users/dgao/.npm/_npx/9434/lib/node_modules/typescript-json-schema/dist/typescript-json-schema.js:1325:23
    at step (/Users/dgao/.npm/_npx/9434/lib/node_modules/typescript-json-schema/dist/typescript-json-schema.js:44:23)
    at Object.next (/Users/dgao/.npm/_npx/9434/lib/node_modules/typescript-json-schema/dist/typescript-json-schema.js:25:53)
    at /Users/dgao/.npm/_npx/9434/lib/node_modules/typescript-json-schema/dist/typescript-json-schema.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/dgao/.npm/_npx/9434/lib/node_modules/typescript-json-schema/dist/typescript-json-schema.js:15:12)
    at exec (/Users/dgao/.npm/_npx/9434/lib/node_modules/typescript-json-schema/dist/typescript-json-schema.js:1302:12)
    at Object.run (/Users/dgao/.npm/_npx/9434/lib/node_modules/typescript-json-schema/dist/typescript-json-schema-cli.js:57:39)
    at Object.<anonymous> (/Users/dgao/.npm/_npx/9434/lib/node_modules/typescript-json-schema/bin/typescript-json-schema:3:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9434) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9434) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
It looks like a dependency error and I have already upgraded this package to the latest version. Any ideas?

**Comment by rexwangcc** [comment]
Ran into the same issue, any ideas?
